name       : haskell-x509-validation
version    : 1.6.10
release    : 2
source     :
    - https://hackage.haskell.org/package/x509-validation-1.6.10/x509-validation-1.6.10.tar.gz : 761c9d77322528259b690508e829cb360feb1fc542951a99f3af51ae980e45d7
license    : BSD-3-Clause
component  : programming.haskell
summary    : X.509 Certificate and CRL validation
description: |
    X.509 Certificate and CRL validation
builddeps  :
    - haskell-byteable
    - haskell-cabal-install
    - haskell-data-default-class
    - haskell-x509-store
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
