name       : haskell-x509-validation
version    : 1.6.11
release    : 3
source     :
    - https://hackage.haskell.org/package/x509-validation-1.6.11/x509-validation-1.6.11.tar.gz : f94321cbcc4a534adf5889ae6950f3673e38b62b89b6970b477f502ce987d19b
license    : BSD-3-Clause
component  : programming.haskell
summary    : X.509 Certificate and CRL validation
description: |
    X.509 Certificate and CRL validation
builddeps  :
    - haskell-cabal-install
    - haskell-data-default-class-devel
    - haskell-x509-store-devel
rundeps    :
    - devel:
        - haskell-data-default-class-devel
        - haskell-x509-store-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
